site_name: "mkdocs-git-revision-date-localized-plugin"
site_description: "Mkdocs plugin that enables displaying the localized date of the last git modification of a markdown file."
copyright: 'Copyright &copy; 2022'
repo_url: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin

nav:
  - index.md
  - available-variables.md
  - How to:
      - howto/specify-locale.md
      - howto/custom-styling.md
      - howto/override-a-theme.md
  - options.md

theme:
    name: material
    custom_dir: docs/overrides
    icon:
        logo: material/calendar-outline
        repo: fontawesome/brands/github
    features:
        - content.tabs.link
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: blue
          accent: blue
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: blue
          accent: blue

plugins:
  - search
  - git-authors:
        exclude:
            - index.md
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true

markdown_extensions:
    - meta
    - admonition
    - pymdownx.keys
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - site/overrides/.icons